// === BEAMLINE COWBOY: GAME DATA ===

// Direction constants for isometric track-laying
const DIR = { NE: 0, SE: 1, SW: 2, NW: 3 };
const DIR_NAMES = ['NE', 'SE', 'SW', 'NW'];
const DIR_DELTA = [
  { dc: 1, dr: -1 },  // NE
  { dc: 1, dr: 1 },   // SE
  { dc: -1, dr: 1 },  // SW
  { dc: -1, dr: -1 }, // NW
];
function turnLeft(dir) { return (dir + 3) % 4; }
function turnRight(dir) { return (dir + 1) % 4; }
function reverseDir(dir) { return (dir + 2) % 4; }

// Isometric tile dimensions
const TILE_W = 64;
const TILE_H = 32;

// Component categories
const CATEGORIES = {
  source: { name: 'Sources', color: '#4a9' },
  magnet: { name: 'Magnets', color: '#c44' },
  rf: { name: 'RF/Accel', color: '#c90' },
  diagnostic: { name: 'Diagnostics', color: '#44c' },
  special: { name: 'Beam Optics', color: '#a4a' },
};

// Components — trackLength replaces w/h; icon and connectDirs removed
const COMPONENTS = {
  source: {
    id: 'source',
    name: 'Source',
    desc: 'Generates a beam of particles. Every beamline needs one.',
    category: 'source',
    cost: { funding: 100 },
    stats: { beamCurrent: 1 },
    energyCost: 5,
    length: 2,
    trackLength: 2,
    maxCount: 2,
    unlocked: true,
    isSource: true,
    spriteKey: 'source',
    spriteColor: 0x44aa99,
  },
  drift: {
    id: 'drift',
    name: 'Drift Tube',
    desc: 'A straight section of beam pipe. Cheap but essential.',
    category: 'source',
    cost: { funding: 20 },
    stats: {},
    energyCost: 0,
    length: 5,
    trackLength: 1,
    unlocked: true,
    spriteKey: 'drift',
    spriteColor: 0x666666,
  },
  dipole: {
    id: 'dipole',
    name: 'Dipole',
    desc: 'Bends the beam 90 degrees. Routes beam around corners.',
    category: 'magnet',
    cost: { funding: 200 },
    stats: { bendAngle: 90 },
    energyCost: 8,
    length: 3,
    trackLength: 2,
    unlocked: true,
    isDipole: true,
    spriteKey: 'dipole',
    spriteColor: 0xaa44aa,
  },
  quadrupole: {
    id: 'quadrupole',
    name: 'Quad',
    desc: 'Focuses the beam to maintain tight bunches.',
    category: 'magnet',
    cost: { funding: 150 },
    stats: { focusStrength: 1 },
    energyCost: 6,
    length: 2,
    trackLength: 1,
    unlocked: true,
    spriteKey: 'quadrupole',
    spriteColor: 0xcc4444,
  },
  rfCavity: {
    id: 'rfCavity',
    name: 'RF Cavity',
    desc: 'Accelerates particles with radio-frequency fields.',
    category: 'rf',
    cost: { funding: 500 },
    stats: { energyGain: 0.5 },
    energyCost: 20,
    length: 4,
    trackLength: 3,
    unlocked: true,
    spriteKey: 'rfCavity',
    spriteColor: 0xcc9900,
  },
  detector: {
    id: 'detector',
    name: 'Detector',
    desc: 'Records particle interactions and generates research data.',
    category: 'diagnostic',
    cost: { funding: 800 },
    stats: { dataRate: 1 },
    energyCost: 15,
    length: 6,
    trackLength: 3,
    unlocked: true,
    spriteKey: 'detector',
    spriteColor: 0x4444cc,
  },
  splitter: {
    id: 'splitter',
    name: 'Splitter',
    desc: 'Splits the beam into two paths. Each path carries half the current.',
    category: 'special',
    cost: { funding: 400 },
    stats: {},
    energyCost: 10,
    length: 2,
    trackLength: 2,
    unlocked: true,
    isSplitter: true,
    spriteKey: 'splitter',
    spriteColor: 0x55aa55,
  },
  undulator: {
    id: 'undulator',
    name: 'Undulator',
    desc: 'Wiggles the beam to produce synchrotron light.',
    category: 'special',
    cost: { funding: 1200 },
    stats: { photonRate: 1 },
    energyCost: 12,
    length: 5,
    trackLength: 3,
    requires: 'synchrotronLight',
    spriteKey: 'undulator',
    spriteColor: 0x6644aa,
  },
  collimator: {
    id: 'collimator',
    name: 'Collimator',
    desc: 'Cleans up the beam by removing stray particles.',
    category: 'special',
    cost: { funding: 300 },
    stats: { beamQuality: 0.2 },
    energyCost: 2,
    length: 2,
    trackLength: 1,
    requires: 'beamOptics',
    spriteKey: 'collimator',
    spriteColor: 0x777744,
  },
  target: {
    id: 'target',
    name: 'Target',
    desc: 'Smashes the beam into a target for nuclear/particle physics.',
    category: 'diagnostic',
    cost: { funding: 600 },
    stats: { collisionRate: 2 },
    energyCost: 0,
    length: 3,
    trackLength: 2,
    requires: 'targetPhysics',
    isEndpoint: true,
    spriteKey: 'target',
    spriteColor: 0x886644,
  },
  cryomodule: {
    id: 'cryomodule',
    name: 'Cryomod',
    desc: 'Superconducting RF cavity. Much higher energy gain.',
    category: 'rf',
    cost: { funding: 2000 },
    stats: { energyGain: 2.0 },
    energyCost: 30,
    length: 5,
    trackLength: 4,
    requires: 'superconducting',
    spriteKey: 'cryomodule',
    spriteColor: 0x4466aa,
  },
  sextupole: {
    id: 'sextupole',
    name: 'Sextupole',
    desc: 'Corrects chromatic aberrations in the beam.',
    category: 'special',
    cost: { funding: 400 },
    stats: { focusStrength: 0.5, beamQuality: 0.3 },
    energyCost: 8,
    length: 2,
    trackLength: 1,
    requires: 'advancedOptics',
    spriteKey: 'sextupole',
    spriteColor: 0x886655,
  },

  // ── Electron Sources ──────────────────────────────────────────────
  dcPhotoGun: {
    id: 'dcPhotoGun',
    name: 'DC Photocathode Gun',
    desc: 'DC photocathode electron source with moderate brightness.',
    category: 'source',
    cost: { funding: 800 },
    stats: { beamCurrent: 1.5 },
    energyCost: 3,
    length: 2,
    trackLength: 2,
    maxCount: 2,
    requires: 'photocathodes',
    isSource: true,
    spriteKey: 'dcPhotoGun',
    spriteColor: 0x44aa99,
    params: { laserWavelength: 532, cathodeQE: 0.01 },
  },
  ncRfGun: {
    id: 'ncRfGun',
    name: 'NC RF Gun',
    desc: 'Normal-conducting RF photoinjector with high peak brightness.',
    category: 'source',
    cost: { funding: 1500 },
    stats: { beamCurrent: 2.5 },
    energyCost: 8,
    length: 2,
    trackLength: 2,
    maxCount: 2,
    requires: 'rfPhotoinjectors',
    isSource: true,
    spriteKey: 'ncRfGun',
    spriteColor: 0x44aa99,
    params: { rfFrequency: 2856, peakField: 120 },
  },
  srfGun: {
    id: 'srfGun',
    name: 'SRF Gun',
    desc: 'Superconducting RF gun for high-average-current CW beams.',
    category: 'source',
    cost: { funding: 5000 },
    stats: { beamCurrent: 4 },
    energyCost: 5,
    length: 3,
    trackLength: 3,
    maxCount: 2,
    requires: 'srfGunTech',
    isSource: true,
    spriteKey: 'srfGun',
    spriteColor: 0x44aa99,
    params: { rfFrequency: 1300, cathodeType: 'Cs2Te' },
  },

  // ── Drift / Beam Pipe ─────────────────────────────────────────────
  bellows: {
    id: 'bellows',
    name: 'Bellows Section',
    desc: 'Flexible vacuum joint to absorb thermal expansion.',
    category: 'source',
    cost: { funding: 30 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    spriteKey: 'bellows',
    spriteColor: 0x666666,
  },

  // ── RF Cavities ───────────────────────────────────────────────────
  buncher: {
    id: 'buncher',
    name: 'Sub-harmonic Buncher',
    desc: 'Compresses particle bunches before injection into the linac.',
    category: 'rf',
    cost: { funding: 400 },
    stats: { bunchCompression: 0.3 },
    energyCost: 3,
    length: 2,
    trackLength: 2,
    requires: 'bunchCompression',
    spriteKey: 'buncher',
    spriteColor: 0xcc9900,
    params: { rfFrequency: 650, voltage: 0.1 },
  },
  harmonicLinearizer: {
    id: 'harmonicLinearizer',
    name: '3.9 GHz Linearizer',
    desc: 'Linearizes the RF curvature for uniform energy distribution.',
    category: 'rf',
    cost: { funding: 600 },
    stats: { bunchCompression: 0.2, beamQuality: 0.2 },
    energyCost: 4,
    length: 2,
    trackLength: 2,
    requires: 'bunchCompression',
    spriteKey: 'harmonicLinearizer',
    spriteColor: 0xcc9900,
    params: { rfFrequency: 3900, voltage: 0.05 },
  },
  cbandCavity: {
    id: 'cbandCavity',
    name: 'C-band NC Cavity',
    desc: 'High-gradient normal-conducting C-band accelerating structure.',
    category: 'rf',
    cost: { funding: 800 },
    stats: { energyGain: 0.8 },
    energyCost: 8,
    length: 2,
    trackLength: 2,
    requires: 'highGradientRf',
    spriteKey: 'cbandCavity',
    spriteColor: 0xcc9900,
    params: { rfFrequency: 5712, gradient: 35 },
  },
  xbandCavity: {
    id: 'xbandCavity',
    name: 'X-band NC Cavity',
    desc: 'Very high gradient X-band structure for compact acceleration.',
    category: 'rf',
    cost: { funding: 1200 },
    stats: { energyGain: 1.2 },
    energyCost: 12,
    length: 2,
    trackLength: 2,
    requires: 'highGradientRf',
    spriteKey: 'xbandCavity',
    spriteColor: 0xcc9900,
    params: { rfFrequency: 11424, gradient: 65 },
  },
  srf650Cavity: {
    id: 'srf650Cavity',
    name: '650 MHz SRF Cavity',
    desc: 'Low-frequency SRF cavity for high-current CW linacs.',
    category: 'rf',
    cost: { funding: 3000 },
    stats: { energyGain: 1.5 },
    energyCost: 4,
    length: 4,
    trackLength: 4,
    requires: 'cwLinacDesign',
    spriteKey: 'srf650Cavity',
    spriteColor: 0x4466aa,
    params: { rfFrequency: 650, gradient: 18, qext: 1e7 },
  },

  // ── Magnets ───────────────────────────────────────────────────────
  solenoid: {
    id: 'solenoid',
    name: 'Solenoid',
    desc: 'Axial magnetic field for low-energy beam focusing.',
    category: 'magnet',
    cost: { funding: 100 },
    stats: { focusStrength: 0.4 },
    energyCost: 1,
    length: 1,
    trackLength: 1,
    spriteKey: 'solenoid',
    spriteColor: 0xcc4444,
    params: { fieldStrength: 0.2 },
  },
  corrector: {
    id: 'corrector',
    name: 'Corrector (H/V)',
    desc: 'Small dipole corrector for orbit steering.',
    category: 'magnet',
    cost: { funding: 80 },
    stats: { beamQuality: 0.05 },
    energyCost: 0.5,
    length: 1,
    trackLength: 1,
    spriteKey: 'corrector',
    spriteColor: 0xcc4444,
    params: { kickAngle: 0.5 },
  },
  octupole: {
    id: 'octupole',
    name: 'Octupole',
    desc: 'Fourth-order correction magnet for Landau damping.',
    category: 'magnet',
    cost: { funding: 500 },
    stats: { beamQuality: 0.15 },
    energyCost: 2,
    length: 1,
    trackLength: 1,
    requires: 'advancedOptics2',
    spriteKey: 'octupole',
    spriteColor: 0xcc4444,
    params: { fieldStrength: 200 },
  },
  scQuad: {
    id: 'scQuad',
    name: 'SC Quadrupole',
    desc: 'Superconducting quadrupole with very high gradient.',
    category: 'magnet',
    cost: { funding: 1000 },
    stats: { focusStrength: 2.5 },
    energyCost: 1,
    length: 1,
    trackLength: 1,
    requires: 'scMagnets',
    spriteKey: 'scQuad',
    spriteColor: 0xcc4444,
    params: { gradient: 150 },
  },
  scDipole: {
    id: 'scDipole',
    name: 'SC Dipole',
    desc: 'Superconducting bending magnet for high-energy beams.',
    category: 'magnet',
    cost: { funding: 2000 },
    stats: { bendAngle: 90 },
    energyCost: 2,
    length: 3,
    trackLength: 2,
    requires: 'scMagnets',
    isDipole: true,
    spriteKey: 'scDipole',
    spriteColor: 0xaa44aa,
    params: { fieldStrength: 6.0 },
  },
  combinedFunctionMagnet: {
    id: 'combinedFunctionMagnet',
    name: 'Combined Function',
    desc: 'Magnet combining dipole bend with quadrupole focusing.',
    category: 'magnet',
    cost: { funding: 1500 },
    stats: { bendAngle: 45, focusStrength: 0.8 },
    energyCost: 2,
    length: 2,
    trackLength: 2,
    requires: 'latticeDesign',
    spriteKey: 'combinedFunctionMagnet',
    spriteColor: 0xcc4444,
    params: { dipoleField: 1.2, quadGradient: 20 },
  },

  // ── Diagnostics ───────────────────────────────────────────────────
  bpm: {
    id: 'bpm',
    name: 'BPM',
    desc: 'Beam Position Monitor — measures orbit on every pulse.',
    category: 'diagnostic',
    cost: { funding: 50 },
    stats: { beamQuality: 0.02 },
    energyCost: 0.1,
    length: 1,
    trackLength: 1,
    spriteKey: 'bpm',
    spriteColor: 0x4444cc,
  },
  screen: {
    id: 'screen',
    name: 'Screen/YAG',
    desc: 'Insertable screen for transverse beam profile imaging.',
    category: 'diagnostic',
    cost: { funding: 100 },
    stats: { beamQuality: 0.03 },
    energyCost: 0.2,
    length: 1,
    trackLength: 1,
    spriteKey: 'screen',
    spriteColor: 0x4444cc,
  },
  ict: {
    id: 'ict',
    name: 'Current Monitor (ICT)',
    desc: 'Integrating current transformer for charge measurement.',
    category: 'diagnostic',
    cost: { funding: 80 },
    stats: {},
    energyCost: 0.1,
    length: 1,
    trackLength: 1,
    spriteKey: 'ict',
    spriteColor: 0x4444cc,
  },
  wireScanner: {
    id: 'wireScanner',
    name: 'Wire Scanner',
    desc: 'Scans a thin wire through the beam for precise emittance.',
    category: 'diagnostic',
    cost: { funding: 300 },
    stats: { beamQuality: 0.05 },
    energyCost: 0.5,
    length: 1,
    trackLength: 1,
    requires: 'beamDiagnostics',
    spriteKey: 'wireScanner',
    spriteColor: 0x4444cc,
  },
  bunchLengthMonitor: {
    id: 'bunchLengthMonitor',
    name: 'Bunch Length Monitor',
    desc: 'Measures longitudinal bunch length via coherent radiation.',
    category: 'diagnostic',
    cost: { funding: 500 },
    stats: {},
    energyCost: 1,
    length: 1,
    trackLength: 1,
    requires: 'beamDiagnostics',
    spriteKey: 'bunchLengthMonitor',
    spriteColor: 0x4444cc,
  },
  energySpectrometer: {
    id: 'energySpectrometer',
    name: 'Energy Spectrometer',
    desc: 'Dispersive section measuring beam energy and energy spread.',
    category: 'diagnostic',
    cost: { funding: 800 },
    stats: { dataRate: 0.3 },
    energyCost: 1,
    length: 2,
    trackLength: 2,
    requires: 'beamDiagnostics',
    spriteKey: 'energySpectrometer',
    spriteColor: 0x4444cc,
  },
  beamLossMonitor: {
    id: 'beamLossMonitor',
    name: 'Beam Loss Monitor',
    desc: 'Detects stray radiation from beam losses for machine protection.',
    category: 'diagnostic',
    cost: { funding: 200 },
    stats: {},
    energyCost: 0.2,
    length: 1,
    trackLength: 1,
    requires: 'machineProtection',
    spriteKey: 'beamLossMonitor',
    spriteColor: 0x4444cc,
  },
  srLightMonitor: {
    id: 'srLightMonitor',
    name: 'SR Light Monitor',
    desc: 'Images synchrotron radiation for beam size measurement.',
    category: 'diagnostic',
    cost: { funding: 400 },
    stats: {},
    energyCost: 0.3,
    length: 1,
    trackLength: 1,
    requires: 'synchrotronLight',
    spriteKey: 'srLightMonitor',
    spriteColor: 0x4444cc,
  },

  // ── Insertion Devices ─────────────────────────────────────────────
  helicalUndulator: {
    id: 'helicalUndulator',
    name: 'Helical Undulator',
    desc: 'Produces circularly polarized photon beams.',
    category: 'special',
    cost: { funding: 2000 },
    stats: { photonRate: 1.5 },
    energyCost: 2,
    length: 5,
    trackLength: 3,
    requires: 'advancedUndulators',
    spriteKey: 'helicalUndulator',
    spriteColor: 0x6644aa,
    params: { period: 30, kParameter: 1.5 },
  },
  wiggler: {
    id: 'wiggler',
    name: 'Wiggler',
    desc: 'High-field insertion device for broadband photon production.',
    category: 'special',
    cost: { funding: 1000 },
    stats: { photonRate: 2 },
    energyCost: 3,
    length: 5,
    trackLength: 3,
    requires: 'synchrotronLight',
    spriteKey: 'wiggler',
    spriteColor: 0x6644aa,
    params: { period: 80, kParameter: 10 },
  },
  apple2Undulator: {
    id: 'apple2Undulator',
    name: 'APPLE-II Undulator',
    desc: 'Variable-polarization undulator for tunable photon beams.',
    category: 'special',
    cost: { funding: 2500 },
    stats: { photonRate: 1.8 },
    energyCost: 2,
    length: 5,
    trackLength: 3,
    requires: 'advancedUndulators',
    spriteKey: 'apple2Undulator',
    spriteColor: 0x6644aa,
    params: { period: 40, kParameter: 2.5, polarization: 'variable' },
  },

  // ── Beam Manipulation ─────────────────────────────────────────────
  kickerMagnet: {
    id: 'kickerMagnet',
    name: 'Kicker Magnet',
    desc: 'Fast pulsed magnet for injection/extraction kicks.',
    category: 'special',
    cost: { funding: 600 },
    stats: {},
    energyCost: 2,
    length: 1,
    trackLength: 1,
    requires: 'fastKickers',
    spriteKey: 'kickerMagnet',
    spriteColor: 0xaa44aa,
    params: { riseTime: 25, kickAngle: 5 },
  },
  septumMagnet: {
    id: 'septumMagnet',
    name: 'Septum Magnet',
    desc: 'Thin-walled magnet separating injected/circulating beams.',
    category: 'special',
    cost: { funding: 800 },
    stats: {},
    energyCost: 2,
    length: 2,
    trackLength: 2,
    requires: 'beamTransport',
    spriteKey: 'septumMagnet',
    spriteColor: 0xaa44aa,
    params: { septumThickness: 2, fieldStrength: 1.0 },
  },
  chicane: {
    id: 'chicane',
    name: 'Chicane (4-dipole)',
    desc: 'Four-dipole bunch compressor chicane.',
    category: 'special',
    cost: { funding: 1200 },
    stats: { bunchCompression: 0.8 },
    energyCost: 3,
    length: 4,
    trackLength: 4,
    requires: 'bunchCompression',
    spriteKey: 'chicane',
    spriteColor: 0xaa44aa,
    params: { r56: -50, bendAngle: 10 },
  },
  dogleg: {
    id: 'dogleg',
    name: 'Dog-leg (2-dipole)',
    desc: 'Two-dipole vertical or horizontal beam offset section.',
    category: 'special',
    cost: { funding: 800 },
    stats: {},
    energyCost: 2,
    length: 3,
    trackLength: 3,
    requires: 'beamTransport',
    spriteKey: 'dogleg',
    spriteColor: 0xaa44aa,
    params: { offset: 0.1, bendAngle: 5 },
  },
  stripperFoil: {
    id: 'stripperFoil',
    name: 'Stripper Foil',
    desc: 'Thin foil that strips electrons from ions for charge exchange.',
    category: 'special',
    cost: { funding: 200 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    requires: 'ionSources',
    spriteKey: 'stripperFoil',
    spriteColor: 0xaa44aa,
    params: { material: 'carbon', thickness: 200 },
  },

  // ── Targets & Endpoints ───────────────────────────────────────────
  fixedTargetAdv: {
    id: 'fixedTargetAdv',
    name: 'Fixed Target (W/LH2)',
    desc: 'Advanced fixed target station with tungsten or liquid hydrogen.',
    category: 'diagnostic',
    cost: { funding: 1500 },
    stats: { collisionRate: 4, dataRate: 1.5 },
    energyCost: 0,
    length: 3,
    trackLength: 3,
    requires: 'targetPhysicsAdv',
    isEndpoint: true,
    spriteKey: 'fixedTargetAdv',
    spriteColor: 0x886644,
    params: { material: 'tungsten', length: 30 },
  },
  photonPort: {
    id: 'photonPort',
    name: 'Photon Beamline Port',
    desc: 'Extraction port for synchrotron or FEL photon beams.',
    category: 'diagnostic',
    cost: { funding: 1000 },
    stats: { dataRate: 1 },
    energyCost: 0,
    length: 2,
    trackLength: 2,
    requires: 'synchrotronLight',
    isEndpoint: true,
    spriteKey: 'photonPort',
    spriteColor: 0x886644,
  },
  positronTarget: {
    id: 'positronTarget',
    name: 'Positron Target',
    desc: 'High-Z target for electron-positron pair production.',
    category: 'diagnostic',
    cost: { funding: 5000 },
    stats: { collisionRate: 2, dataRate: 2 },
    energyCost: 0,
    length: 3,
    trackLength: 3,
    requires: 'antimatter',
    isEndpoint: true,
    spriteKey: 'positronTarget',
    spriteColor: 0x886644,
    params: { material: 'tungsten', thickness: 14 },
  },
  comptonIP: {
    id: 'comptonIP',
    name: 'Compton Backscatter IP',
    desc: 'Compton scattering interaction point for gamma-ray production.',
    category: 'diagnostic',
    cost: { funding: 3000 },
    stats: { dataRate: 1.5 },
    energyCost: 1,
    length: 3,
    trackLength: 3,
    requires: 'photonScience',
    isEndpoint: true,
    spriteKey: 'comptonIP',
    spriteColor: 0x886644,
    params: { laserWavelength: 1064, crossingAngle: 5 },
  },

  // ══════════════════════════════════════════════════════════════════
  // INFRASTRUCTURE COMPONENTS
  // ══════════════════════════════════════════════════════════════════

  // ── RF Power ──────────────────────────────────────────────────────
  solidStateAmp: {
    id: 'solidStateAmp',
    name: 'Solid-State Amplifier',
    desc: 'Low-power solid-state RF amplifier.',
    category: 'rf',
    cost: { funding: 200 },
    stats: {},
    energyCost: 2,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'solidStateAmp',
    spriteColor: 0xcc9900,
  },
  pulsedKlystron: {
    id: 'pulsedKlystron',
    name: 'Pulsed Klystron',
    desc: 'High-power pulsed klystron for NC accelerating structures.',
    category: 'rf',
    cost: { funding: 1000 },
    stats: {},
    energyCost: 10,
    length: 2,
    trackLength: 2,
    isInfrastructure: true,
    spriteKey: 'pulsedKlystron',
    spriteColor: 0xcc9900,
    params: { peakPower: 50, pulseLength: 5 },
  },
  cwKlystron: {
    id: 'cwKlystron',
    name: 'CW Klystron',
    desc: 'Continuous-wave klystron for SRF cavity drive.',
    category: 'rf',
    cost: { funding: 2000 },
    stats: {},
    energyCost: 15,
    length: 2,
    trackLength: 2,
    requires: 'cwRfSystems',
    isInfrastructure: true,
    spriteKey: 'cwKlystron',
    spriteColor: 0xcc9900,
    params: { cwPower: 10, efficiency: 0.55 },
  },
  modulator: {
    id: 'modulator',
    name: 'Modulator',
    desc: 'Provides high-voltage pulses to drive klystrons.',
    category: 'rf',
    cost: { funding: 500 },
    stats: {},
    energyCost: 3,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'modulator',
    spriteColor: 0xcc9900,
  },
  iot: {
    id: 'iot',
    name: 'IOT',
    desc: 'Inductive Output Tube for efficient CW RF generation.',
    category: 'rf',
    cost: { funding: 1500 },
    stats: {},
    energyCost: 8,
    length: 2,
    trackLength: 2,
    requires: 'cwRfSystems',
    isInfrastructure: true,
    spriteKey: 'iot',
    spriteColor: 0xcc9900,
    params: { cwPower: 80, efficiency: 0.70 },
  },
  circulator: {
    id: 'circulator',
    name: 'Circulator/Load',
    desc: 'Protects the RF source by absorbing reflected power.',
    category: 'rf',
    cost: { funding: 150 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'circulator',
    spriteColor: 0xcc9900,
  },
  waveguide: {
    id: 'waveguide',
    name: 'Waveguide Run',
    desc: 'Rectangular waveguide carrying RF power to cavities.',
    category: 'rf',
    cost: { funding: 50 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'waveguide',
    spriteColor: 0xcc9900,
  },
  rfCoupler: {
    id: 'rfCoupler',
    name: 'High-Power Coupler',
    desc: 'Transfers RF power from waveguide into the cavity.',
    category: 'rf',
    cost: { funding: 300 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'rfCoupler',
    spriteColor: 0xcc9900,
  },
  llrfController: {
    id: 'llrfController',
    name: 'LLRF Controller',
    desc: 'Digital low-level RF controller for cavity field regulation.',
    category: 'rf',
    cost: { funding: 400 },
    stats: {},
    energyCost: 0.5,
    length: 1,
    trackLength: 1,
    requires: 'digitalLlrf',
    isInfrastructure: true,
    spriteKey: 'llrfController',
    spriteColor: 0xcc9900,
    params: { bandwidth: 1e6, loopGain: 30 },
  },
  multibeamKlystron: {
    id: 'multibeamKlystron',
    name: 'Multi-beam Klystron',
    desc: 'High-efficiency multi-beam klystron for MW-class RF.',
    category: 'rf',
    cost: { funding: 3000 },
    stats: {},
    energyCost: 12,
    length: 2,
    trackLength: 2,
    requires: 'advancedRf',
    isInfrastructure: true,
    spriteKey: 'multibeamKlystron',
    spriteColor: 0xcc9900,
    params: { peakPower: 100, efficiency: 0.65 },
  },
  highPowerSSA: {
    id: 'highPowerSSA',
    name: 'High-Power SS Transmitter',
    desc: 'Modular high-power solid-state RF transmitter.',
    category: 'rf',
    cost: { funding: 2500 },
    stats: {},
    energyCost: 10,
    length: 2,
    trackLength: 2,
    requires: 'advancedRf',
    isInfrastructure: true,
    spriteKey: 'highPowerSSA',
    spriteColor: 0xcc9900,
    params: { cwPower: 300, efficiency: 0.60 },
  },

  // ── Cryogenics ────────────────────────────────────────────────────
  heCompressor: {
    id: 'heCompressor',
    name: 'Helium Compressor',
    desc: 'Compresses helium gas for the cryogenic plant.',
    category: 'rf',
    cost: { funding: 3000 },
    stats: {},
    energyCost: 20,
    length: 3,
    trackLength: 3,
    requires: 'srfTechnology',
    isInfrastructure: true,
    spriteKey: 'heCompressor',
    spriteColor: 0x4466aa,
  },
  coldBox4K: {
    id: 'coldBox4K',
    name: '4K Cold Box',
    desc: 'Refrigerator cold box producing 4.5 K helium.',
    category: 'rf',
    cost: { funding: 5000 },
    stats: {},
    energyCost: 15,
    length: 4,
    trackLength: 4,
    requires: 'srfTechnology',
    isInfrastructure: true,
    spriteKey: 'coldBox4K',
    spriteColor: 0x4466aa,
    params: { coolingCapacity: 500, temperature: 4.5 },
  },
  coldBox2K: {
    id: 'coldBox2K',
    name: '2K Cold Box',
    desc: 'Sub-atmospheric cold box for 2 K superfluid helium.',
    category: 'rf',
    cost: { funding: 8000 },
    stats: {},
    energyCost: 25,
    length: 4,
    trackLength: 4,
    requires: 'highQSrf',
    isInfrastructure: true,
    spriteKey: 'coldBox2K',
    spriteColor: 0x4466aa,
    params: { coolingCapacity: 200, temperature: 2.0 },
  },
  cryomoduleHousing: {
    id: 'cryomoduleHousing',
    name: 'Cryomodule Housing',
    desc: 'Vacuum vessel and thermal shielding for SRF cavities.',
    category: 'rf',
    cost: { funding: 2000 },
    stats: {},
    energyCost: 2,
    length: 4,
    trackLength: 4,
    requires: 'srfTechnology',
    isInfrastructure: true,
    spriteKey: 'cryomoduleHousing',
    spriteColor: 0x4466aa,
  },
  transferLine: {
    id: 'transferLine',
    name: 'Cryogenic Transfer Line',
    desc: 'Insulated piping carrying cryogens between plant and tunnel.',
    category: 'rf',
    cost: { funding: 200 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    requires: 'srfTechnology',
    isInfrastructure: true,
    spriteKey: 'transferLine',
    spriteColor: 0x4466aa,
  },
  ln2Precooler: {
    id: 'ln2Precooler',
    name: 'LN2 Pre-cooler',
    desc: 'Liquid nitrogen pre-cooling stage to reduce helium plant load.',
    category: 'rf',
    cost: { funding: 1000 },
    stats: {},
    energyCost: 5,
    length: 2,
    trackLength: 2,
    requires: 'srfTechnology',
    isInfrastructure: true,
    spriteKey: 'ln2Precooler',
    spriteColor: 0x4466aa,
  },
  heRecovery: {
    id: 'heRecovery',
    name: 'Helium Recovery/Storage',
    desc: 'Recovers and stores boil-off helium gas for reuse.',
    category: 'rf',
    cost: { funding: 2000 },
    stats: {},
    energyCost: 3,
    length: 3,
    trackLength: 3,
    requires: 'cryoOptimization',
    isInfrastructure: true,
    spriteKey: 'heRecovery',
    spriteColor: 0x4466aa,
  },
  cryocooler: {
    id: 'cryocooler',
    name: 'Cryocooler (small)',
    desc: 'Small closed-cycle cryocooler for SC magnet cooling.',
    category: 'rf',
    cost: { funding: 800 },
    stats: {},
    energyCost: 5,
    length: 1,
    trackLength: 1,
    requires: 'scMagnets',
    isInfrastructure: true,
    spriteKey: 'cryocooler',
    spriteColor: 0x4466aa,
  },

  // ── Vacuum ────────────────────────────────────────────────────────
  roughingPump: {
    id: 'roughingPump',
    name: 'Roughing Pump',
    desc: 'Mechanical pump for initial vacuum pump-down.',
    category: 'special',
    cost: { funding: 100 },
    stats: {},
    energyCost: 0.5,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'roughingPump',
    spriteColor: 0x777744,
  },
  turboPump: {
    id: 'turboPump',
    name: 'Turbo Pump',
    desc: 'Turbomolecular pump for high-vacuum operation.',
    category: 'special',
    cost: { funding: 300 },
    stats: {},
    energyCost: 1,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'turboPump',
    spriteColor: 0x777744,
  },
  ionPump: {
    id: 'ionPump',
    name: 'Ion Pump',
    desc: 'Sputter ion pump for maintenance-free UHV operation.',
    category: 'special',
    cost: { funding: 500 },
    stats: {},
    energyCost: 0.3,
    length: 1,
    trackLength: 1,
    requires: 'uhvSystems',
    isInfrastructure: true,
    spriteKey: 'ionPump',
    spriteColor: 0x777744,
  },
  negPump: {
    id: 'negPump',
    name: 'NEG Pump',
    desc: 'Non-evaporable getter pump for distributed pumping.',
    category: 'special',
    cost: { funding: 400 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    requires: 'uhvSystems',
    isInfrastructure: true,
    spriteKey: 'negPump',
    spriteColor: 0x777744,
  },
  tiSubPump: {
    id: 'tiSubPump',
    name: 'Ti Sublimation Pump',
    desc: 'Titanium sublimation pump for extreme vacuum levels.',
    category: 'special',
    cost: { funding: 350 },
    stats: {},
    energyCost: 0.5,
    length: 1,
    trackLength: 1,
    requires: 'uhvSystems',
    isInfrastructure: true,
    spriteKey: 'tiSubPump',
    spriteColor: 0x777744,
  },
  piraniGauge: {
    id: 'piraniGauge',
    name: 'Pirani Gauge',
    desc: 'Thermal conductivity gauge for rough vacuum measurement.',
    category: 'diagnostic',
    cost: { funding: 30 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'piraniGauge',
    spriteColor: 0x4444cc,
  },
  coldCathodeGauge: {
    id: 'coldCathodeGauge',
    name: 'Cold Cathode Gauge',
    desc: 'Inverted magnetron gauge for high-vacuum pressure readout.',
    category: 'diagnostic',
    cost: { funding: 50 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'coldCathodeGauge',
    spriteColor: 0x4444cc,
  },
  baGauge: {
    id: 'baGauge',
    name: 'BA Gauge',
    desc: 'Bayard-Alpert gauge for UHV pressure measurement.',
    category: 'diagnostic',
    cost: { funding: 100 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    requires: 'uhvSystems',
    isInfrastructure: true,
    spriteKey: 'baGauge',
    spriteColor: 0x4444cc,
  },
  gateValve: {
    id: 'gateValve',
    name: 'Gate Valve',
    desc: 'Isolates vacuum sectors for maintenance access.',
    category: 'special',
    cost: { funding: 200 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'gateValve',
    spriteColor: 0x777744,
  },
  bakeoutSystem: {
    id: 'bakeoutSystem',
    name: 'Bakeout System',
    desc: 'Heats vacuum chambers to desorb gas and reach UHV.',
    category: 'special',
    cost: { funding: 500 },
    stats: {},
    energyCost: 5,
    length: 2,
    trackLength: 2,
    requires: 'uhvSystems',
    isInfrastructure: true,
    spriteKey: 'bakeoutSystem',
    spriteColor: 0x777744,
  },

  // ── Cooling Water ─────────────────────────────────────────────────
  lcwSkid: {
    id: 'lcwSkid',
    name: 'LCW Skid',
    desc: 'Low-conductivity water skid for magnet and cavity cooling.',
    category: 'rf',
    cost: { funding: 500 },
    stats: {},
    energyCost: 3,
    length: 2,
    trackLength: 2,
    isInfrastructure: true,
    spriteKey: 'lcwSkid',
    spriteColor: 0xcc9900,
  },
  chiller: {
    id: 'chiller',
    name: 'Chiller',
    desc: 'Chilled water plant for temperature-critical components.',
    category: 'rf',
    cost: { funding: 800 },
    stats: {},
    energyCost: 5,
    length: 3,
    trackLength: 3,
    isInfrastructure: true,
    spriteKey: 'chiller',
    spriteColor: 0xcc9900,
  },
  coolingTower: {
    id: 'coolingTower',
    name: 'Cooling Tower',
    desc: 'Evaporative cooling tower rejecting waste heat.',
    category: 'rf',
    cost: { funding: 1000 },
    stats: {},
    energyCost: 4,
    length: 3,
    trackLength: 3,
    isInfrastructure: true,
    spriteKey: 'coolingTower',
    spriteColor: 0xcc9900,
  },
  heatExchanger: {
    id: 'heatExchanger',
    name: 'Heat Exchanger',
    desc: 'Transfers heat between cooling circuits.',
    category: 'rf',
    cost: { funding: 300 },
    stats: {},
    energyCost: 1,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'heatExchanger',
    spriteColor: 0xcc9900,
  },
  waterLoad: {
    id: 'waterLoad',
    name: 'High-Power Water Load',
    desc: 'Absorbs high-power RF into water for safe dissipation.',
    category: 'rf',
    cost: { funding: 200 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'waterLoad',
    spriteColor: 0xcc9900,
  },
  deionizer: {
    id: 'deionizer',
    name: 'Deionizer/Water Treatment',
    desc: 'Maintains water resistivity for LCW systems.',
    category: 'rf',
    cost: { funding: 400 },
    stats: {},
    energyCost: 1,
    length: 2,
    trackLength: 2,
    requires: 'facilitySystems',
    isInfrastructure: true,
    spriteKey: 'deionizer',
    spriteColor: 0xcc9900,
  },
  emergencyCooling: {
    id: 'emergencyCooling',
    name: 'Emergency Cooling (UPS)',
    desc: 'Battery-backed cooling for safe shutdown during power loss.',
    category: 'rf',
    cost: { funding: 1500 },
    stats: {},
    energyCost: 0,
    length: 2,
    trackLength: 2,
    requires: 'machineProtection',
    isInfrastructure: true,
    spriteKey: 'emergencyCooling',
    spriteColor: 0xcc9900,
  },

  // ── Controls & Safety ─────────────────────────────────────────────
  rackIoc: {
    id: 'rackIoc',
    name: 'Rack/IOC',
    desc: 'Electronics rack with IOC for EPICS-based control.',
    category: 'diagnostic',
    cost: { funding: 200 },
    stats: {},
    energyCost: 0.5,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'rackIoc',
    spriteColor: 0x4444cc,
  },
  ppsInterlock: {
    id: 'ppsInterlock',
    name: 'PPS Interlock',
    desc: 'Personnel protection system interlock module.',
    category: 'diagnostic',
    cost: { funding: 300 },
    stats: {},
    energyCost: 0.2,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'ppsInterlock',
    spriteColor: 0x4444cc,
  },
  shielding: {
    id: 'shielding',
    name: 'Beam Containment Shielding',
    desc: 'Concrete and lead shielding for radiation containment.',
    category: 'special',
    cost: { funding: 400 },
    stats: {},
    energyCost: 0,
    length: 2,
    trackLength: 2,
    isInfrastructure: true,
    spriteKey: 'shielding',
    spriteColor: 0x777744,
  },
  mps: {
    id: 'mps',
    name: 'Machine Protection System',
    desc: 'Fast interlock system to dump beam on fault detection.',
    category: 'diagnostic',
    cost: { funding: 1000 },
    stats: {},
    energyCost: 0.5,
    length: 1,
    trackLength: 1,
    requires: 'machineProtection',
    isInfrastructure: true,
    spriteKey: 'mps',
    spriteColor: 0x4444cc,
  },
  areaMonitor: {
    id: 'areaMonitor',
    name: 'Radiation Monitor',
    desc: 'Area radiation monitor for personnel safety.',
    category: 'diagnostic',
    cost: { funding: 150 },
    stats: {},
    energyCost: 0.1,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'areaMonitor',
    spriteColor: 0x4444cc,
  },
  timingSystem: {
    id: 'timingSystem',
    name: 'Timing System',
    desc: 'Machine-wide timing distribution for synchronized triggers.',
    category: 'diagnostic',
    cost: { funding: 600 },
    stats: {},
    energyCost: 0.5,
    length: 1,
    trackLength: 1,
    requires: 'digitalLlrf',
    isInfrastructure: true,
    spriteKey: 'timingSystem',
    spriteColor: 0x4444cc,
  },
  laserSystem: {
    id: 'laserSystem',
    name: 'Laser System (gun drive)',
    desc: 'Pulsed UV laser system driving the photocathode gun.',
    category: 'source',
    cost: { funding: 2000 },
    stats: {},
    energyCost: 3,
    length: 2,
    trackLength: 2,
    requires: 'photocathodes',
    isInfrastructure: true,
    spriteKey: 'laserSystem',
    spriteColor: 0x44aa99,
    params: { wavelength: 266, pulseEnergy: 50 },
  },
  laserHeater: {
    id: 'laserHeater',
    name: 'Laser Heater',
    desc: 'Laser heater to suppress microbunching instability.',
    category: 'special',
    cost: { funding: 3000 },
    stats: {},
    energyCost: 4,
    length: 2,
    trackLength: 2,
    requires: 'felPhysics',
    isInfrastructure: true,
    spriteKey: 'laserHeater',
    spriteColor: 0xaa44aa,
  },

  // ── Electrical Power ──────────────────────────────────────────────
  substation: {
    id: 'substation',
    name: 'Substation/Transformer',
    desc: 'Main power substation providing facility electrical capacity.',
    category: 'rf',
    cost: { funding: 1000 },
    stats: {},
    energyCost: 0,
    powerCapacity: 500,
    length: 4,
    trackLength: 4,
    isInfrastructure: true,
    spriteKey: 'substation',
    spriteColor: 0xcc9900,
  },
  powerPanel: {
    id: 'powerPanel',
    name: 'Power Distribution Panel',
    desc: 'Distributes electrical power to local equipment.',
    category: 'rf',
    cost: { funding: 200 },
    stats: {},
    energyCost: 0,
    length: 1,
    trackLength: 1,
    isInfrastructure: true,
    spriteKey: 'powerPanel',
    spriteColor: 0xcc9900,
  },
};

const RESEARCH = {
  // === TIER 1 — Beam Science Basics ===
  beamOptics: {
    id: 'beamOptics',
    name: 'Beam Optics',
    desc: 'Shape and clean beams. Unlocks Collimator, Sextupole, Velocity Selector.',
    cost: { data: 10, funding: 500 },
    duration: 30,
    unlocks: ['collimator', 'sextupole'],
    requires: null,
    tier: 1,
  },
  beamDiagnostics: {
    id: 'beamDiagnostics',
    name: 'Beam Diagnostics',
    desc: 'Advanced measurement techniques. Unlocks Wire Scanner, Bunch Length Monitor, Energy Spectrometer.',
    cost: { data: 10, funding: 500 },
    duration: 30,
    unlocks: ['wireScanner', 'bunchLengthMonitor', 'energySpectrometer'],
    requires: null,
    tier: 1,
  },
  bunchCompression: {
    id: 'bunchCompression',
    name: 'Bunch Compression',
    desc: 'Compress bunches to femtosecond lengths. Unlocks Buncher, Chicane, Dog-leg, Harmonic Linearizer.',
    cost: { data: 15, funding: 1000 },
    duration: 45,
    unlocks: ['buncher', 'chicane', 'dogleg', 'harmonicLinearizer'],
    requires: 'beamOptics',
    tier: 1,
  },
  targetPhysics: {
    id: 'targetPhysics',
    name: 'Target Physics',
    desc: 'Study fixed-target collisions. Unlocks Fixed Target (Be, Cu).',
    cost: { data: 15, funding: 1000 },
    duration: 45,
    unlocks: ['target'],
    requires: null,
    tier: 1,
  },
  machineProtection: {
    id: 'machineProtection',
    name: 'Machine Protection',
    desc: 'Fast beam abort and loss monitoring. Unlocks MPS, BLM, Emergency Cooling.',
    cost: { data: 15, funding: 1000 },
    duration: 40,
    unlocks: ['mps', 'beamLossMonitor', 'emergencyCooling'],
    requires: 'beamDiagnostics',
    tier: 1,
  },

  // === TIER 2 — CW & Photon Capability ===
  photocathodes: {
    id: 'photocathodes',
    name: 'Photocathodes',
    desc: 'High-brightness electron sources. Unlocks DC Photocathode Gun, Laser System.',
    cost: { data: 25, funding: 3000 },
    duration: 60,
    unlocks: ['dcPhotoGun', 'laserSystem'],
    requires: 'beamDiagnostics',
    tier: 2,
  },
  cwRfSystems: {
    id: 'cwRfSystems',
    name: 'CW RF Systems',
    desc: 'Continuous-wave RF power. Unlocks CW Klystron, IOT.',
    cost: { data: 25, funding: 3000 },
    duration: 60,
    unlocks: ['cwKlystron', 'iot'],
    requires: 'bunchCompression',
    tier: 2,
  },
  synchrotronLight: {
    id: 'synchrotronLight',
    name: 'Synchrotron Light',
    desc: 'Harness photon beams. Unlocks Undulator, Wiggler, SR Light Monitor, Photon Port.',
    cost: { data: 30, funding: 5000 },
    duration: 70,
    unlocks: ['undulator', 'wiggler', 'srLightMonitor', 'photonPort'],
    requires: 'beamOptics',
    tier: 2,
  },
  uhvSystems: {
    id: 'uhvSystems',
    name: 'UHV Systems',
    desc: 'Ultra-high vacuum techniques. Unlocks Ion Pump, NEG Pump, TSP, BA Gauge, Bakeout.',
    cost: { data: 20, funding: 2000 },
    duration: 50,
    unlocks: ['ionPump', 'negPump', 'tiSubPump', 'baGauge', 'bakeoutSystem'],
    requires: null,
    tier: 2,
  },
  facilitySystems: {
    id: 'facilitySystems',
    name: 'Facility Systems',
    desc: 'Facility-grade utilities. Unlocks Deionizer/Water Treatment.',
    cost: { data: 15, funding: 2000 },
    duration: 40,
    unlocks: ['deionizer'],
    requires: null,
    tier: 2,
  },
  digitalLlrf: {
    id: 'digitalLlrf',
    name: 'Digital LLRF',
    desc: 'Precision RF field control. Unlocks LLRF Controller, Timing System.',
    cost: { data: 25, funding: 3000 },
    duration: 50,
    unlocks: ['llrfController', 'timingSystem'],
    requires: 'cwRfSystems',
    tier: 2,
  },
  dataAnalysis: {
    id: 'dataAnalysis',
    name: 'Data Analysis',
    desc: 'Better algorithms for detector signals. 2x data rate.',
    cost: { data: 20, funding: 2000 },
    duration: 40,
    effect: { dataRateMult: 2 },
    requires: null,
    tier: 2,
  },

  // === TIER 3 — SRF & Advanced Magnets ===
  srfTechnology: {
    id: 'srfTechnology',
    name: 'SRF Technology',
    desc: 'Superconducting RF cavities. Unlocks L-band SRF Cavity, Cryomodule, Cryo Plant, Transfer Lines.',
    cost: { data: 50, funding: 10000, reputation: 5 },
    duration: 90,
    unlocks: ['cryomodule', 'cryomoduleHousing', 'heCompressor', 'coldBox4K', 'transferLine', 'ln2Precooler'],
    requires: 'cwRfSystems',
    tier: 3,
  },
  superconducting: {
    id: 'superconducting',
    name: 'Superconducting RF',
    desc: 'Legacy SRF research. Enables basic cryomodule access.',
    cost: { data: 50, funding: 10000, reputation: 5 },
    duration: 90,
    unlocks: ['cryomodule'],
    requires: 'cwRfSystems',
    hidden: true, // merged into srfTechnology, kept for save compat
    tier: 3,
  },
  scMagnets: {
    id: 'scMagnets',
    name: 'SC Magnets',
    desc: 'Superconducting magnets for stronger fields. Unlocks SC Quad, SC Dipole, Cryocooler.',
    cost: { data: 40, funding: 8000, reputation: 5 },
    duration: 80,
    unlocks: ['scQuad', 'scDipole', 'cryocooler'],
    requires: 'beamOptics',
    tier: 3,
  },
  rfPhotoinjectors: {
    id: 'rfPhotoinjectors',
    name: 'RF Photoinjectors',
    desc: 'High-gradient photocathode guns. Unlocks NC RF Gun.',
    cost: { data: 40, funding: 8000 },
    duration: 70,
    unlocks: ['ncRfGun'],
    requires: ['photocathodes', 'digitalLlrf'],
    tier: 3,
  },
  beamTransport: {
    id: 'beamTransport',
    name: 'Beam Transport',
    desc: 'Beam extraction and splitting. Unlocks Septum Magnet.',
    cost: { data: 30, funding: 5000 },
    duration: 60,
    unlocks: ['septumMagnet'],
    requires: 'beamOptics',
    tier: 3,
  },
  latticeDesign: {
    id: 'latticeDesign',
    name: 'Lattice Design',
    desc: 'Optimized magnet arrangements. Unlocks Combined Function Magnet.',
    cost: { data: 35, funding: 6000 },
    duration: 65,
    unlocks: ['combinedFunctionMagnet'],
    requires: 'scMagnets',
    tier: 3,
  },
  automation: {
    id: 'automation',
    name: 'Automation',
    desc: 'Automated tuning and control. +$2/s passive funding.',
    cost: { data: 25, funding: 3000 },
    duration: 50,
    effect: { passiveFunding: 2 },
    requires: 'dataAnalysis',
    tier: 3,
  },
  energyRecovery: {
    id: 'energyRecovery',
    name: 'Energy Recovery',
    desc: 'Recoup energy from beams. 30% energy cost reduction.',
    cost: { data: 35, funding: 5000 },
    duration: 60,
    effect: { energyCostMult: 0.7 },
    requires: 'srfTechnology',
    tier: 3,
  },

  // === TIER 4 — High Performance ===
  highQSrf: {
    id: 'highQSrf',
    name: 'High-Q SRF',
    desc: '2K operation for ultra-high Q0. Unlocks 2K Cold Box, Helium Recovery.',
    cost: { data: 60, funding: 15000, reputation: 10 },
    duration: 100,
    unlocks: ['coldBox2K', 'heRecovery'],
    requires: 'srfTechnology',
    tier: 4,
  },
  highGradientRf: {
    id: 'highGradientRf',
    name: 'High Gradient RF',
    desc: 'Push accelerating gradients higher. Unlocks C-band, X-band Cavities.',
    cost: { data: 50, funding: 12000 },
    duration: 90,
    unlocks: ['cbandCavity', 'xbandCavity'],
    requires: 'rfPhotoinjectors',
    tier: 4,
  },
  advancedRf: {
    id: 'advancedRf',
    name: 'Advanced RF',
    desc: 'Next-gen RF sources. Unlocks Multi-beam Klystron, High-Power SSA.',
    cost: { data: 50, funding: 12000 },
    duration: 90,
    unlocks: ['multibeamKlystron', 'highPowerSSA'],
    requires: ['cwRfSystems', 'digitalLlrf'],
    tier: 4,
  },
  cwLinacDesign: {
    id: 'cwLinacDesign',
    name: 'CW Linac Design',
    desc: 'High-current CW linacs. Unlocks 650 MHz SRF Cavity.',
    cost: { data: 60, funding: 15000, reputation: 10 },
    duration: 100,
    unlocks: ['srf650Cavity'],
    requires: ['srfTechnology', 'highQSrf'],
    tier: 4,
  },
  fastKickers: {
    id: 'fastKickers',
    name: 'Fast Kickers',
    desc: 'Nanosecond beam switching. Unlocks Kicker Magnet.',
    cost: { data: 40, funding: 8000 },
    duration: 70,
    unlocks: ['kickerMagnet'],
    requires: 'beamTransport',
    tier: 4,
  },
  advancedOptics: {
    id: 'advancedOptics',
    name: 'Advanced Optics',
    desc: 'Higher-order corrections. Unlocks Octupole.',
    cost: { data: 40, funding: 8000 },
    duration: 70,
    unlocks: ['sextupole', 'octupole'],
    requires: 'latticeDesign',
    tier: 4,
  },
  advancedUndulators: {
    id: 'advancedUndulators',
    name: 'Advanced Undulators',
    desc: 'Variable polarization. Unlocks Helical Undulator, APPLE-II.',
    cost: { data: 50, funding: 12000 },
    duration: 90,
    unlocks: ['helicalUndulator', 'apple2Undulator'],
    requires: 'synchrotronLight',
    tier: 4,
  },
  felPhysics: {
    id: 'felPhysics',
    name: 'FEL Physics',
    desc: 'Free-electron laser physics. Unlocks Laser Heater.',
    cost: { data: 60, funding: 15000, reputation: 10 },
    duration: 100,
    unlocks: ['laserHeater'],
    requires: ['advancedUndulators', 'bunchCompression'],
    tier: 4,
  },
  highLuminosity: {
    id: 'highLuminosity',
    name: 'High Luminosity',
    desc: 'Squeeze beams tighter for more collisions. 2x luminosity.',
    cost: { data: 40, funding: 8000 },
    duration: 70,
    effect: { luminosityMult: 2 },
    requires: 'advancedOptics',
    tier: 4,
  },
  particleDiscovery: {
    id: 'particleDiscovery',
    name: 'Particle Discovery',
    desc: 'New techniques to discover exotic particles. +10% discovery chance.',
    cost: { data: 80, funding: 20000 },
    duration: 120,
    effect: { discoveryChance: 0.1 },
    requires: 'highLuminosity',
    tier: 4,
  },

  // === TIER 5 — Frontier ===
  srfGunTech: {
    id: 'srfGunTech',
    name: 'SRF Gun Technology',
    desc: 'Ultimate brightness electron source. Unlocks SRF Gun.',
    cost: { data: 80, funding: 25000, reputation: 15 },
    duration: 120,
    unlocks: ['srfGun'],
    requires: ['srfTechnology', 'rfPhotoinjectors'],
    tier: 5,
  },
  cryoOptimization: {
    id: 'cryoOptimization',
    name: 'Cryo Optimization',
    desc: 'Improved helium recovery, reduced static loads.',
    cost: { data: 60, funding: 15000 },
    duration: 100,
    unlocks: ['heRecovery'],
    effect: { cryoEfficiencyMult: 0.7 },
    requires: 'highQSrf',
    tier: 5,
  },
  antimatter: {
    id: 'antimatter',
    name: 'Antimatter',
    desc: 'Positron production via pair creation. Unlocks Positron Target.',
    cost: { data: 100, funding: 50000, reputation: 20 },
    duration: 150,
    unlocks: ['positronTarget'],
    requires: ['highGradientRf', 'targetPhysics'],
    tier: 5,
  },
  photonScience: {
    id: 'photonScience',
    name: 'Photon Science',
    desc: 'Compton backscattering and advanced photon techniques.',
    cost: { data: 80, funding: 25000, reputation: 15 },
    duration: 120,
    unlocks: ['comptonIP'],
    requires: 'felPhysics',
    tier: 5,
  },
  targetPhysicsAdv: {
    id: 'targetPhysicsAdv',
    name: 'Target Physics (Advanced)',
    desc: 'High-Z targets for extreme experiments. Unlocks W/LH2 Targets.',
    cost: { data: 60, funding: 15000, reputation: 10 },
    duration: 100,
    unlocks: ['fixedTargetAdv'],
    requires: ['targetPhysics', 'machineProtection'],
    tier: 5,
  },
};

const OBJECTIVES = [
  // === Tier 0 — Getting Started ===
  {
    id: 'firstBeam',
    name: 'First Beam!',
    desc: 'Build a source and turn on the beam.',
    condition: (state) => state.beamOn && state.beamline.some(n => COMPONENTS[n.type]?.isSource),
    reward: { funding: 500, reputation: 1 },
    tier: 0,
  },
  {
    id: 'firstMeasurement',
    name: 'First Measurement',
    desc: 'Place a BPM and measure beam position.',
    condition: (state) => state.beamOn && state.beamline.some(n => n.type === 'bpm'),
    reward: { funding: 300, reputation: 1 },
    tier: 0,
  },
  {
    id: 'stableBeam',
    name: 'Stable Beam',
    desc: 'Run beam for 60 continuous seconds.',
    condition: (state) => state.continuousBeamTicks >= 60,
    reward: { funding: 500, reputation: 1 },
    tier: 0,
  },

  // === Tier 1 — Basic Competence ===
  {
    id: 'reach100mev',
    name: '100 MeV',
    desc: 'Reach a beam energy of 100 MeV.',
    condition: (state) => state.beamEnergy >= 0.1,
    reward: { funding: 1000, reputation: 2 },
    tier: 1,
  },
  {
    id: 'beamCharacterization',
    name: 'Beam Characterization',
    desc: 'Measure emittance, energy, and current simultaneously.',
    condition: (state) => {
      const types = state.beamline.map(n => n.type);
      return types.includes('wireScanner') && types.includes('energySpectrometer') && types.includes('ict');
    },
    reward: { funding: 500, reputation: 2 },
    tier: 1,
  },
  {
    id: 'firstUser',
    name: 'First User',
    desc: 'Build a photon port and deliver beam hours.',
    condition: (state) => state.totalBeamHours >= 1 && state.beamline.some(n => n.type === 'photonPort'),
    reward: { funding: 2000, reputation: 3 },
    tier: 1,
  },
  {
    id: 'goodVacuum',
    name: 'Good Vacuum',
    desc: 'Achieve average pressure below 1e-8 mbar.',
    condition: (state) => state.avgPressure !== undefined && state.avgPressure < 1e-8,
    reward: { funding: 500, reputation: 1 },
    tier: 1,
  },
  {
    id: 'firstResearch',
    name: 'Knowledge Seeker',
    desc: 'Complete your first research project.',
    condition: (state) => state.completedResearch.length >= 1,
    reward: { funding: 500, reputation: 2 },
    tier: 1,
  },
  {
    id: 'firstData',
    name: 'First Light',
    desc: 'Collect 10 units of research data.',
    condition: (state) => state.totalDataCollected >= 10,
    reward: { funding: 300, reputation: 1 },
    tier: 1,
  },

  // === Tier 2 — Real Facility ===
  {
    id: 'reach1gev',
    name: 'GeV Club',
    desc: 'Reach a beam energy of 1 GeV.',
    condition: (state) => state.beamEnergy >= 1,
    reward: { funding: 5000, reputation: 5 },
    tier: 2,
  },
  {
    id: 'cwOperation',
    name: 'CW Operation',
    desc: 'Run CW beam for 300 continuous seconds.',
    condition: (state) => state.continuousBeamTicks >= 300,
    reward: { funding: 3000, reputation: 3 },
    tier: 2,
  },
  {
    id: 'subMicronEmittance',
    name: 'Sub-micron Emittance',
    desc: 'Achieve normalized emittance below 1 \u03bcm at >100 MeV.',
    condition: (state) => state.beamEnergy >= 0.1 && state.finalNormEmittanceX !== undefined && state.finalNormEmittanceX < 1e-6,
    reward: { funding: 3000, reputation: 5 },
    tier: 2,
  },
  {
    id: 'fiveUsers',
    name: 'Five Users',
    desc: 'Serve 5 simultaneous photon beamline ports.',
    condition: (state) => state.beamline.filter(n => n.type === 'photonPort').length >= 5,
    reward: { funding: 10000, reputation: 10 },
    tier: 2,
  },
  {
    id: 'firstTarget',
    name: 'First Target',
    desc: 'Run beam on a fixed target.',
    condition: (state) => state.beamOn && state.beamline.some(n => COMPONENTS[n.type]?.isEndpoint),
    reward: { funding: 3000, reputation: 5 },
    tier: 2,
  },
  {
    id: 'tenComponents',
    name: 'Growing Machine',
    desc: 'Install 10 components on your beamline.',
    condition: (state) => state.beamline.length >= 10,
    reward: { funding: 800, reputation: 2 },
    tier: 2,
  },
  {
    id: 'collect100data',
    name: 'Data Hoarder',
    desc: 'Collect 100 units of research data.',
    condition: (state) => state.totalDataCollected >= 100,
    reward: { funding: 1500, reputation: 3 },
    tier: 2,
  },
  {
    id: 'threeResearch',
    name: 'Research Program',
    desc: 'Complete 3 research projects.',
    condition: (state) => state.completedResearch.length >= 3,
    reward: { funding: 2000, reputation: 5 },
    tier: 2,
  },

  // === Tier 3 — World Class ===
  {
    id: 'reach10gev',
    name: '10 GeV',
    desc: 'Reach a beam energy of 10 GeV.',
    condition: (state) => state.beamEnergy >= 10,
    reward: { funding: 20000, reputation: 10 },
    tier: 3,
  },
  {
    id: 'srfLinac',
    name: 'SRF Linac',
    desc: 'Operate 10 or more SRF cavities simultaneously.',
    condition: (state) => state.beamline.filter(n => n.type === 'cryomodule' || n.type === 'srf650Cavity').length >= 10,
    reward: { funding: 10000, reputation: 5 },
    tier: 3,
  },
  {
    id: 'bunchCompressed',
    name: 'Bunch Compression',
    desc: 'Achieve bunch length below 100 fs.',
    condition: (state) => state.finalBunchLength !== undefined && state.finalBunchLength < 100e-15,
    reward: { funding: 5000, reputation: 10 },
    tier: 3,
  },
  {
    id: 'felSaturation',
    name: 'FEL Saturation',
    desc: 'Achieve free-electron laser saturation.',
    condition: (state) => state.felSaturated === true,
    reward: { funding: 50000, reputation: 20 },
    tier: 3,
  },
  {
    id: 'highAvailability',
    name: 'High Availability',
    desc: 'Maintain 95% uptime over 1000 ticks.',
    condition: (state) => state.tick >= 1000 && state.uptimeFraction >= 0.95,
    reward: { funding: 10000, reputation: 10 },
    tier: 3,
  },
  {
    id: 'collect1000data',
    name: 'Big Data',
    desc: 'Collect 1,000 units of research data.',
    condition: (state) => state.totalDataCollected >= 1000,
    reward: { funding: 5000, reputation: 10 },
    tier: 3,
  },
  {
    id: 'userFacility',
    name: 'User Facility',
    desc: 'Reach 10 reputation.',
    condition: (state) => state.resources.reputation >= 10,
    reward: { funding: 3000 },
    tier: 3,
  },

  // === Tier 4 — Frontier ===
  {
    id: 'reach100gev',
    name: '100 GeV',
    desc: 'Reach a beam energy of 100 GeV.',
    condition: (state) => state.beamEnergy >= 100,
    reward: { funding: 100000, reputation: 30 },
    tier: 4,
  },
  {
    id: 'particleDiscoveryObj',
    name: 'Particle Discovery',
    desc: 'Observe a new particle.',
    condition: (state) => state.discoveries >= 1,
    reward: { funding: 200000, reputation: 50 },
    tier: 4,
  },
  {
    id: 'positronBeam',
    name: 'Positron Beam',
    desc: 'Generate and accelerate positrons.',
    condition: (state) => state.beamline.some(n => n.type === 'positronTarget') && state.beamOn,
    reward: { funding: 50000, reputation: 30 },
    tier: 4,
  },
  {
    id: 'tenPublications',
    name: '10 Publications',
    desc: 'Accumulate 10 research milestone completions.',
    condition: (state) => state.completedResearch.length >= 10,
    reward: { reputation: 20 },
    tier: 4,
  },
  {
    id: 'nationalLab',
    name: 'National Lab Status',
    desc: 'Reach 100 reputation.',
    condition: (state) => state.resources.reputation >= 100,
    reward: { funding: 500000 },
    tier: 4,
  },
  {
    id: 'allResearch',
    name: 'Omniscient',
    desc: 'Complete all research projects.',
    condition: (state) => {
      const nonHidden = Object.values(RESEARCH).filter(r => !r.hidden);
      return state.completedResearch.length >= nonHidden.length;
    },
    reward: { funding: 10000, reputation: 20 },
    tier: 4,
  },

  // === Tier 5 — Legacy ===
  {
    id: 'nobelPrize',
    name: 'Nobel Prize',
    desc: 'Discover a fundamental particle at frontier energy.',
    condition: (state) => state.discoveries >= 1 && state.beamEnergy >= 100,
    reward: { funding: 1000000, reputation: 100 },
    tier: 5,
  },
  {
    id: 'userFacilityOfYear',
    name: 'User Facility of the Year',
    desc: 'Deliver 10,000 total beam hours.',
    condition: (state) => state.totalBeamHours >= 10000,
    reward: { funding: 200000, reputation: 50 },
    tier: 5,
  },
  {
    id: 'fullCatalog',
    name: 'Full Catalog',
    desc: 'Build every component type at least once.',
    condition: (state) => {
      const builtTypes = new Set(state.beamline.map(n => n.type));
      const allTypes = Object.keys(COMPONENTS);
      return allTypes.every(t => builtTypes.has(t));
    },
    reward: { funding: 100000, reputation: 30 },
    tier: 5,
  },
];
